#############################################################################
# Makefile for building: Platformer
# Generated by qmake (3.1) (Qt 5.12.3)
# Project:  Platformer.pro
# Template: app
# Command: /opt/felgo/Felgo/gcc_64/bin/qmake -o Makefile Platformer.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/felgo/Felgo/gcc_64/include/Felgo -I/opt/felgo/Felgo/gcc_64/include -I/opt/felgo/Felgo/gcc_64/include/QtQuick -I/opt/felgo/Felgo/gcc_64/include/QtWidgets -I/opt/felgo/Felgo/gcc_64/include/QtMultimedia -I/opt/felgo/Felgo/gcc_64/include/QtGui -I/opt/felgo/Felgo/gcc_64/include/QtQml -I/opt/felgo/Felgo/gcc_64/include/QtWebSockets -I/opt/felgo/Felgo/gcc_64/include/QtNetwork -I/opt/felgo/Felgo/gcc_64/include/QtSql -I/opt/felgo/Felgo/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I/opt/felgo/Felgo/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/felgo/Felgo/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/felgo/Felgo/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/felgo/Felgo/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Platformer1.0.0
DISTDIR = /root/Platformer/.tmp/Platformer1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/felgo/Felgo/gcc_64/lib
LIBS          = $(SUBLIBS) -L/opt/felgo/Felgo/gcc_64/lib -lFelgo -lz -lQt5Quick -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5Qml -lQt5WebSockets -lQt5Network -lQt5Sql -lQt5Core -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qml/scenes/saveandupdate.cpp \
		qml/scenes/gameplayer.cpp qrc_resources_user.cpp \
		moc_saveandupdate.cpp \
		moc_gameplayer.cpp
OBJECTS       = main.o \
		saveandupdate.o \
		gameplayer.o \
		qrc_resources_user.o \
		moc_saveandupdate.o \
		moc_gameplayer.o
DIST          = qml/commond/MenuButton.qml \
		qml/entities/Ground1.qml \
		qml/levels/Level2.qml \
		qml/entities/EnemyBase.qml \
		qml/entities/Coin.qml \
		qml/entities/EnemyPet.qml \
		qml/entities/EnemyCrystallo.qml \
		qml/scenes/Scoresranking.qml \
		qml/entities/Finish.qml \
		qml/entities/EnemyXiezi.qml \
		qml/entities/EnemyDragon.qml \
		qml/entities/EnemyMonster.qml \
		qml/entities/EnemySnail.qml \
		qml/entities/EnemyIceBlock.qml \
		qml/entities/Diamond.qml \
		qml/entities/Magic.qml \
		qml/entities/EnemyFHead.qml \
		qml/entities/Bullet.qml \
		qml/entities/Water.qml \
		qml/entities/Brick.qml \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/unix.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/linux.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/sanitize.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/g++-base.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/qconfig.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/qt_config.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/spec_post.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/toolchain.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/default_pre.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/default_post.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/felgo.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/warn_on.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/qt.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/resources.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/moc.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/uic.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/file_copies.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/exceptions.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/yacc.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/lex.prf \
		Platformer.pro qml/scenes/saveandupdate.h \
		qml/scenes/gameplayer.h main.cpp \
		qml/scenes/saveandupdate.cpp \
		qml/scenes/gameplayer.cpp
QMAKE_TARGET  = Platformer
DESTDIR       = 
TARGET        = Platformer


first: all
####### Build rules

Platformer:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Platformer.pro /opt/felgo/Felgo/gcc_64/mkspecs/linux-g++/qmake.conf /opt/felgo/Felgo/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/unix.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/linux.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/sanitize.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/g++-base.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/qconfig.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/qt_config.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/spec_post.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/toolchain.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/default_pre.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/default_post.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/felgo.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/warn_on.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/qt.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/resources.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/moc.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/uic.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/file_copies.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/exceptions.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/yacc.prf \
		/opt/felgo/Felgo/gcc_64/mkspecs/features/lex.prf \
		Platformer.pro \
		/opt/felgo/Felgo/gcc_64/mkspecs/common/felgo/resources_user.qrc \
		/opt/felgo/Felgo/gcc_64/lib/libQt5Quick.prl \
		/opt/felgo/Felgo/gcc_64/lib/libQt5Widgets.prl \
		/opt/felgo/Felgo/gcc_64/lib/libQt5Multimedia.prl \
		/opt/felgo/Felgo/gcc_64/lib/libQt5Gui.prl \
		/opt/felgo/Felgo/gcc_64/lib/libQt5Qml.prl \
		/opt/felgo/Felgo/gcc_64/lib/libQt5WebSockets.prl \
		/opt/felgo/Felgo/gcc_64/lib/libQt5Network.prl \
		/opt/felgo/Felgo/gcc_64/lib/libQt5Sql.prl \
		/opt/felgo/Felgo/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Platformer.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/opt/felgo/Felgo/gcc_64/mkspecs/features/spec_pre.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/common/unix.conf:
/opt/felgo/Felgo/gcc_64/mkspecs/common/linux.conf:
/opt/felgo/Felgo/gcc_64/mkspecs/common/sanitize.conf:
/opt/felgo/Felgo/gcc_64/mkspecs/common/gcc-base.conf:
/opt/felgo/Felgo/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/felgo/Felgo/gcc_64/mkspecs/common/g++-base.conf:
/opt/felgo/Felgo/gcc_64/mkspecs/common/g++-unix.conf:
/opt/felgo/Felgo/gcc_64/mkspecs/qconfig.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/felgo/Felgo/gcc_64/mkspecs/features/qt_functions.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/qt_config.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/spec_post.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/toolchain.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/default_pre.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/resolve_config.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/default_post.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/felgo.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/qml_debug.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/warn_on.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/qt.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/resources.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/moc.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/uic.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/unix/thread.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/qmake_use.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/file_copies.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/exceptions.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/yacc.prf:
/opt/felgo/Felgo/gcc_64/mkspecs/features/lex.prf:
Platformer.pro:
/opt/felgo/Felgo/gcc_64/mkspecs/common/felgo/resources_user.qrc:
/opt/felgo/Felgo/gcc_64/lib/libQt5Quick.prl:
/opt/felgo/Felgo/gcc_64/lib/libQt5Widgets.prl:
/opt/felgo/Felgo/gcc_64/lib/libQt5Multimedia.prl:
/opt/felgo/Felgo/gcc_64/lib/libQt5Gui.prl:
/opt/felgo/Felgo/gcc_64/lib/libQt5Qml.prl:
/opt/felgo/Felgo/gcc_64/lib/libQt5WebSockets.prl:
/opt/felgo/Felgo/gcc_64/lib/libQt5Network.prl:
/opt/felgo/Felgo/gcc_64/lib/libQt5Sql.prl:
/opt/felgo/Felgo/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Platformer.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile Platformer

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/felgo/Felgo/gcc_64/mkspecs/common/felgo/resources_user.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/felgo/Felgo/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents qml/scenes/saveandupdate.h qml/scenes/gameplayer.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp qml/scenes/saveandupdate.cpp qml/scenes/gameplayer.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources_user.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources_user.cpp
qrc_resources_user.cpp: /opt/felgo/Felgo/gcc_64/mkspecs/common/felgo/resources_user.qrc \
		/opt/felgo/Felgo/gcc_64/bin/rcc \
		/opt/felgo/Felgo/felgo_license.key
	/opt/felgo/Felgo/gcc_64/bin/rcc -name resources_user /opt/felgo/Felgo/gcc_64/mkspecs/common/felgo/resources_user.qrc -o qrc_resources_user.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/felgo/Felgo/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -W -dM -E -o moc_predefs.h /opt/felgo/Felgo/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_saveandupdate.cpp moc_gameplayer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_saveandupdate.cpp moc_gameplayer.cpp
moc_saveandupdate.cpp: qml/scenes/saveandupdate.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QObject \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobject.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qnamespace.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qconfig.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtcore-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsysinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlogging.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qflags.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmutex.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qnumeric.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qversiontagging.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstring.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qchar.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbytearray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qrefcount.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qarraydata.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringliteral.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringview.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qalgorithms.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qiterator.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qpair.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringlist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qregexp.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcoreevent.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmetatype.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobject_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/QList \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qevent.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qtgui-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qregion.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qrect.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmargins.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsize.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qpoint.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdatastream.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qiodevice.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qkeysequence.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvariant.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmap.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdebug.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qhash.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtextstream.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlocale.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qshareddata.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvector.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qset.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qurl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qurlquery.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qfile.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qfiledevice.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qvector2d.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/QQmlListProperty \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqmllist.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qtqmlglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qtqml-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QString \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonDocument \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsondocument.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsonvalue.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonArray \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsonarray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonObject \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsonobject.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonValue \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonParseError \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QDebug \
		qml/scenes/gameplayer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QDateTime \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdatetime.h \
		moc_predefs.h \
		/opt/felgo/Felgo/gcc_64/bin/moc
	/opt/felgo/Felgo/gcc_64/bin/moc $(DEFINES) --include /root/Platformer/moc_predefs.h -I/opt/felgo/Felgo/gcc_64/mkspecs/linux-g++ -I/root/Platformer -I/opt/felgo/Felgo/gcc_64/include/Felgo -I/opt/felgo/Felgo/gcc_64/include -I/opt/felgo/Felgo/gcc_64/include/QtQuick -I/opt/felgo/Felgo/gcc_64/include/QtWidgets -I/opt/felgo/Felgo/gcc_64/include/QtMultimedia -I/opt/felgo/Felgo/gcc_64/include/QtGui -I/opt/felgo/Felgo/gcc_64/include/QtQml -I/opt/felgo/Felgo/gcc_64/include/QtWebSockets -I/opt/felgo/Felgo/gcc_64/include/QtNetwork -I/opt/felgo/Felgo/gcc_64/include/QtSql -I/opt/felgo/Felgo/gcc_64/include/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include-fixed -I/usr/include qml/scenes/saveandupdate.h -o moc_saveandupdate.cpp

moc_gameplayer.cpp: qml/scenes/gameplayer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QObject \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobject.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qnamespace.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qconfig.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtcore-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsysinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlogging.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qflags.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmutex.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qnumeric.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qversiontagging.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstring.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qchar.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbytearray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qrefcount.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qarraydata.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringliteral.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringview.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qalgorithms.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qiterator.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qpair.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringlist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qregexp.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcoreevent.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmetatype.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobject_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QString \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QDateTime \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdatetime.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qshareddata.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qhash.h \
		moc_predefs.h \
		/opt/felgo/Felgo/gcc_64/bin/moc
	/opt/felgo/Felgo/gcc_64/bin/moc $(DEFINES) --include /root/Platformer/moc_predefs.h -I/opt/felgo/Felgo/gcc_64/mkspecs/linux-g++ -I/root/Platformer -I/opt/felgo/Felgo/gcc_64/include/Felgo -I/opt/felgo/Felgo/gcc_64/include -I/opt/felgo/Felgo/gcc_64/include/QtQuick -I/opt/felgo/Felgo/gcc_64/include/QtWidgets -I/opt/felgo/Felgo/gcc_64/include/QtMultimedia -I/opt/felgo/Felgo/gcc_64/include/QtGui -I/opt/felgo/Felgo/gcc_64/include/QtQml -I/opt/felgo/Felgo/gcc_64/include/QtWebSockets -I/opt/felgo/Felgo/gcc_64/include/QtNetwork -I/opt/felgo/Felgo/gcc_64/include/QtSql -I/opt/felgo/Felgo/gcc_64/include/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/include-fixed -I/usr/include qml/scenes/gameplayer.h -o moc_gameplayer.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /opt/felgo/Felgo/gcc_64/include/QtWidgets/QApplication \
		/opt/felgo/Felgo/gcc_64/include/QtWidgets/qapplication.h \
		/opt/felgo/Felgo/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qconfig.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtcore-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsysinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlogging.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qflags.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmutex.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qnumeric.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qversiontagging.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qtgui-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstring.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qchar.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbytearray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qrefcount.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qnamespace.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qarraydata.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringliteral.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringview.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobject.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qalgorithms.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qiterator.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qpair.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringlist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qregexp.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcoreevent.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmetatype.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobject_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qeventloop.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qpoint.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsize.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qcursor.h \
		/opt/felgo/Felgo/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/felgo/Felgo/gcc_64/include/QtWidgets/qwidget.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmargins.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qrect.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qpalette.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qcolor.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qrgb.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qrgba64.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qbrush.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvector.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qmatrix.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qpolygon.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qregion.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdatastream.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qiodevice.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qline.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qtransform.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qpainterpath.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qimage.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qpixelformat.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qpixmap.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qshareddata.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qhash.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qfont.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qfontinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qkeysequence.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qevent.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvariant.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmap.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdebug.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtextstream.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlocale.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qset.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qurl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qurlquery.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qfile.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qfiledevice.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qvector2d.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qguiapplication.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qinputmethod.h \
		/opt/felgo/Felgo/gcc_64/include/Felgo/FelgoApplication \
		/opt/felgo/Felgo/gcc_64/include/Felgo/felgoapplication.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QObject \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QAbstractAnimation \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qabstractanimation.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QStringList \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QVariantMap \
		/opt/felgo/Felgo/gcc_64/include/QtQml/QQmlApplicationEngine \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqmlapplicationengine.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqmlengine.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qjsengine.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qjsvalue.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qtqmlglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qtqml-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqmldebug.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqml.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqmlprivate.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqmlparserstatus.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqmllist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmetaobject.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqmlerror.h \
		qml/scenes/gameplayer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QString \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QDateTime \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdatetime.h \
		qml/scenes/saveandupdate.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/QList \
		/opt/felgo/Felgo/gcc_64/include/QtQml/QQmlListProperty \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonDocument \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsondocument.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsonvalue.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonArray \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsonarray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonObject \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsonobject.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonValue \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonParseError \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

saveandupdate.o: qml/scenes/saveandupdate.cpp qml/scenes/saveandupdate.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QObject \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobject.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qnamespace.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qconfig.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtcore-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsysinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlogging.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qflags.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmutex.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qnumeric.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qversiontagging.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstring.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qchar.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbytearray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qrefcount.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qarraydata.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringliteral.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringview.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qalgorithms.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qiterator.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qpair.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringlist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qregexp.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcoreevent.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmetatype.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobject_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/QList \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qevent.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qtgui-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qregion.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qrect.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmargins.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsize.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qpoint.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdatastream.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qiodevice.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qkeysequence.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvariant.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmap.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdebug.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qhash.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtextstream.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlocale.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qshareddata.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvector.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qset.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qurl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qurlquery.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qfile.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qfiledevice.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qvector2d.h \
		/opt/felgo/Felgo/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/QQmlListProperty \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qqmllist.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qtqmlglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtQml/qtqml-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QString \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonDocument \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsondocument.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsonvalue.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonArray \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsonarray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonObject \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qjsonobject.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonValue \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QJsonParseError \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QDebug \
		qml/scenes/gameplayer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QDateTime \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdatetime.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QDir \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdir.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o saveandupdate.o qml/scenes/saveandupdate.cpp

gameplayer.o: qml/scenes/gameplayer.cpp qml/scenes/gameplayer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QObject \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobject.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qnamespace.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qglobal.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qconfig.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtcore-config.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qsysinfo.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlogging.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qflags.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmutex.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qnumeric.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qversiontagging.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstring.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qchar.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbytearray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qrefcount.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qarraydata.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringliteral.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringview.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qlist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qalgorithms.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qiterator.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qpair.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringlist.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qregexp.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcoreevent.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qmetatype.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qobject_impl.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QString \
		/opt/felgo/Felgo/gcc_64/include/QtCore/QDateTime \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qdatetime.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qshareddata.h \
		/opt/felgo/Felgo/gcc_64/include/QtCore/qhash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameplayer.o qml/scenes/gameplayer.cpp

qrc_resources_user.o: qrc_resources_user.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources_user.o qrc_resources_user.cpp

moc_saveandupdate.o: moc_saveandupdate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_saveandupdate.o moc_saveandupdate.cpp

moc_gameplayer.o: moc_gameplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameplayer.o moc_gameplayer.cpp

####### Install

install_itemqmlFolder: first FORCE
	@test -d $(INSTALL_ROOT)/root/Platformer || mkdir -p $(INSTALL_ROOT)/root/Platformer
	-$(QINSTALL) /root/Platformer/qml $(INSTALL_ROOT)/root/Platformer/qml

uninstall_itemqmlFolder: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/root/Platformer/qml
	-$(DEL_DIR) $(INSTALL_ROOT)/root/Platformer/ 


install_itemassetsFolder: first FORCE
	@test -d $(INSTALL_ROOT)/root/Platformer || mkdir -p $(INSTALL_ROOT)/root/Platformer
	-$(QINSTALL) /root/Platformer/assets $(INSTALL_ROOT)/root/Platformer/assets

uninstall_itemassetsFolder: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/root/Platformer/assets
	-$(DEL_DIR) $(INSTALL_ROOT)/root/Platformer/ 


install: install_itemqmlFolder install_itemassetsFolder  FORCE

uninstall: uninstall_itemqmlFolder uninstall_itemassetsFolder  FORCE

FORCE:

